chore!: module from template and tests updated
mineiros-io/terraform-google-identity-group pull request #19
Opened 2022-09-26 16:50 UTC by waxb

- chore: changelog updated
- chore: module from template and tests updated
- fix: `initial_group_config` validation

2022-09-27 09:54 UTC, mariux requested changes

2022-09-27 09:54 UTC, mariux commented on CHANGELOG.md
> +- `initial_group_config` validation excluded 'INITIAL_GROUP_CONFIG_UNSPECIFIED', now it is accepted
```suggestion
- Fix `initial_group_config` validation to include 'INITIAL_GROUP_CONFIG_UNSPECIFIED'
```

2022-09-27 09:54 UTC, mariux commented on CHANGELOG.md
> +- README updated
```suggestion
- Add unit tests
```

2022-09-27 09:54 UTC, mariux commented on versions.tf
> +  required_version = "~> 1.0"
change is missing in change log and this is a breaking change! ;)

2022-09-27 09:54 UTC, mariux commented on variables.tf
> +    condition     = contains(["WITH_INITIAL_OWNER", "EMPTY", "INITIAL_GROUP_CONFIG_UNSPECIFIED"], var.initial_group_config)
nice catch

2022-09-27 09:54 UTC, mariux commented on test/unit-minimal/_generated_google.tf
> +  directory_customer_id = try(data.google_organization.org[0].directory_customer_id, "no-directory-customer")
please do not rename the variable.

2022-09-27 14:42 UTC, waxb commented on test/unit-minimal/_generated_google.tf
> +  directory_customer_id = try(data.google_organization.org[0].directory_customer_id, "no-directory-customer")
it was `directory_customer_id` in the template both getting value from `google_organization.org[0].directory_customer_id` so this seems the consistent way. what do you think?

2022-09-27 14:43 UTC, waxb commented on test/unit-minimal/_generated_google.tf
> +  directory_customer_id = try(data.google_organization.org[0].directory_customer_id, "no-directory-customer")
https://github.com/mineiros-io/terraform-google-identity-group/blob/7e3ac9d268bf1388a63d322356d341a6ce7308ce/test/terramate_google.tm.hcl#L75


https://github.com/mineiros-io/terraform-module-template/blob/b139cde8b396283a130e7df93693e2e1a8ccd335/test/terramate_google.tm.hcl#L83

2022-09-27 14:44 UTC, waxb commented on test/unit-minimal/_generated_google.tf
> +  directory_customer_id = try(data.google_organization.org[0].directory_customer_id, "no-directory-customer")
also changed in the relevant parts (e.g.: https://github.com/mineiros-io/terraform-google-identity-group/blob/3eb295990195bc690274c483f0fe65cf171b6c42/test/unit-complete/main.tf#L8 )

2022-10-07 12:00 UTC, zied-elouaer approved these changes
LGTM!

2022-10-08 17:01 UTC, mariux approved these changes
lgtm

2022-10-10 08:46 UTC, merged