docs: update outputs
mineiros-io/terraform-google-identity-group pull request #8
Opened 2022-01-24 21:50 UTC by kassianh

2022-01-26 11:44 UTC, soerenmartius requested changes

2022-01-26 11:44 UTC, soerenmartius commented on README.tfdoc.hcl
>          All attributes of the created 'google_cloud_identity_group' resource.
```suggestion
        All attributes of the created `google_cloud_identity_group` resource.
```

2022-01-26 11:44 UTC, soerenmartius commented on README.tfdoc.hcl
>          All attributes of the created 'google_cloud_identity_group_membership' resource.
```suggestion
        All attributes of the created `google_cloud_identity_group_membership` resource.
```

2022-01-26 19:01 UTC, mariux requested changes

2022-02-01 18:38 UTC, mariux approved these changes
lgtm

2022-02-01 18:39 UTC, merged